### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by rodeoric** [pikachunakapika/BitCrack#1]
Hello, 

is there any way to get a compiled version of your git ?

I do not see a cuBitCrack.exe or something or can i just use the one from brichard ? But how your changes can be integrated then ? 

Thank you so much.

**Comment by pikachunakapika** [comment]
Hi, 
I will create binaries when all work is done and tested and also send a pull request to brichard so he can merge if he wants to.

Best Regards

**Comment by pikachunakapika** [comment]
@ZielarSRC was so nice and created binaries:

https://github.com/ZielarSRC/BitCrack/releases

**Comment by pikachunakapika** [comment]
Releases available now

**Comment by rodeoric** [comment]
You both guys are god damned great. 

THANK YOU !
