### ISSUE TITLE
VanitySearch

### ISSUE THREAD

**Issue by broka77** [pikachunakapika/BitCrack#11]
I'm sorry I created the topic not there, i can not create an Issue...
VanitySearch does not compile on ubuntu, writes the wrong version of gcc> 7 I can not fix ... can you help?

**Comment by broka77** [comment]
please compile binary file for ubuntu/linux

**Comment by pikachunakapika** [comment]
Hi, sorry for the circumstances. VanitySearch modifications were not finished yet. I will publish updates soon.
