### ISSUE TITLE
random vs starting point

### ISSUE THREAD

**Issue by hamnaz** [pikachunakapika/BitCrack#6]
Hello all
i notice, this random called update just start with random starting points instead of series starting points
after 1st generates random starting points, each starting point  start searching series,
Random should be every second each every string random

if you understand, its ok, if you need to understand more in details with example, feel free to ask

**Comment by pikachunakapika** [comment]
Hi, 
I know what you mean. This would be very nice. Unfortunately generating the random starting points is very slow. So every second BitCrack would start the "Generating starting points" phase for a few seconds.

You could alternatively add a random stride?

Best Regards
